ssr_api:
    path:     /api/{stock}/{city}
    defaults: { _controller: SSRBundle:Default:api, stock: 'stops', city: 'krakow' }
    
ssr_homepage:
    path:     /{city}
    defaults: { _controller: SSRBundle:Default:index, city: 'krakow' }
    